theme: jekyll-theme-Architect
encoding: utf-8
title: 身体作为支点
description: 在 Obsidian 写作，推送到 GitHub 后可在浏览器阅读
favicon: /favicon.ico

url: https://alphaveteran.github.io
baseurl: /body-as-fulcrum

defaults:
  - scope:
      path: "fulcrum"
      type: "pages"
    values:
      layout: "fulcrum-post"
  - scope:
      path: "fulcrum/index.html"
      type: "pages"
    values:
      layout: "fulcrum-home"
